package com.inspiredandroid.braincup.games

import braincup.composeapp.generated.resources.*
import org.jetbrains.compose.resources.StringResource

enum class GameType(
    val displayNameRes: StringResource,
    val id: String,
    val goldScore: Int,
    val silverScore: Int,
    val descriptionRes: StringResource,
    val accentColor: Long,
) {
    ANOMALY_PUZZLE(
        displayNameRes = Res.string.game_anomaly_puzzle,
        id = "6",
        goldScore = 17,
        silverScore = 8,
        descriptionRes = Res.string.game_anomaly_puzzle_desc,
        accentColor = 0xFFFFE4E6,
    ),
    PATH_FINDER(
        displayNameRes = Res.string.game_path_finder,
        id = "8",
        goldScore = 14,
        silverScore = 7,
        descriptionRes = Res.string.game_path_finder_desc,
        accentColor = 0xFFE0F2FE,
    ),
    GHOST_GRID(
        displayNameRes = Res.string.game_ghost_grid,
        id = "12",
        goldScore = 8,
        silverScore = 5,
        descriptionRes = Res.string.game_ghost_grid_desc,
        accentColor = 0xFFE2E8F0,
    ),
    VISUAL_MEMORY(
        displayNameRes = Res.string.game_visual_memory,
        id = "10",
        goldScore = 9,
        silverScore = 6,
        descriptionRes = Res.string.game_visual_memory_desc,
        accentColor = 0xFFD1FAE5,
    ),
    COLORED_SHAPES(
        displayNameRes = Res.string.game_colored_shapes,
        id = "1",
        goldScore = 15,
        silverScore = 8,
        descriptionRes = Res.string.game_colored_shapes_desc,
        accentColor = 0xFFFCE7F3,
    ),
    SHERLOCK_CALCULATION(
        displayNameRes = Res.string.game_sherlock_calculation,
        id = "2",
        goldScore = 7,
        silverScore = 3,
        descriptionRes = Res.string.game_sherlock_calculation_desc,
        accentColor = 0xFFFEF3C7,
    ),
    MENTAL_CALCULATION(
        displayNameRes = Res.string.game_mental_calculation,
        id = "0",
        goldScore = 16,
        silverScore = 8,
        descriptionRes = Res.string.game_mental_calculation_desc,
        accentColor = 0xFFDBEAFE,
    ),
    CHAIN_CALCULATION(
        displayNameRes = Res.string.game_chain_calculation,
        id = "3",
        goldScore = 8,
        silverScore = 4,
        descriptionRes = Res.string.game_chain_calculation_desc,
        accentColor = 0xFFCCFBF1,
    ),
    FRACTION_CALCULATION(
        displayNameRes = Res.string.game_fraction_calculation,
        id = "4",
        goldScore = 12,
        silverScore = 4,
        descriptionRes = Res.string.game_fraction_calculation_desc,
        accentColor = 0xFFE0E7FF,
    ),
    VALUE_COMPARISON(
        displayNameRes = Res.string.game_value_comparison,
        id = "5",
        goldScore = 14,
        silverScore = 4,
        descriptionRes = Res.string.game_value_comparison_desc,
        accentColor = 0xFFECFCCB,
    ),
    GRID_SOLVER(
        displayNameRes = Res.string.game_grid_solver,
        id = "9",
        goldScore = 6,
        silverScore = 3,
        descriptionRes = Res.string.game_grid_solver_desc,
        accentColor = 0xFFEDE9FE,
    ),
    PATTERN_SEQUENCE(
        displayNameRes = Res.string.game_pattern_sequence,
        id = "11",
        goldScore = 10,
        silverScore = 5,
        descriptionRes = Res.string.game_pattern_sequence_desc,
        accentColor = 0xFFFFEDD5,
    ),
    COLOR_CONFUSION(
        displayNameRes = Res.string.game_color_confusion,
        id = "13",
        goldScore = 12,
        silverScore = 6,
        descriptionRes = Res.string.game_color_confusion_desc,
        accentColor = 0xFFFAE8FF,
    ),
    ORBIT_TRACKER(
        displayNameRes = Res.string.game_orbit_tracker,
        id = "14",
        goldScore = 8,
        silverScore = 4,
        descriptionRes = Res.string.game_orbit_tracker_desc,
        accentColor = 0xFFCFFAFE,
    ),
    FLASH_CROWD(
        displayNameRes = Res.string.game_flash_crowd,
        id = "15",
        goldScore = 18,
        silverScore = 12,
        descriptionRes = Res.string.game_flash_crowd_desc,
        accentColor = 0xFFFEF9C3,
    ),
}

fun getGameTypeById(id: String): GameType? = GameType.entries.find { it.id == id }
