default_platform(:android)

platform :android do
  desc "Upload localized screenshots to Play Store"
  lane :upload_screenshots do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: false,
      skip_upload_metadata: false,
    )
  end
end
