package com.inspiredandroid.braincup.ui.screens

import braincup.composeapp.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource

fun flagResource(slug: String): DrawableResource = when (slug) {
    "afghanistan" -> Res.drawable.flag_afghanistan_50
    "aland_islands" -> Res.drawable.flag_aland_islands_50
    "albania" -> Res.drawable.flag_albania_50
    "algeria" -> Res.drawable.flag_algeria_50
    "andorra" -> Res.drawable.flag_andorra_50
    "angola" -> Res.drawable.flag_angola_50
    "anguilla" -> Res.drawable.flag_anguilla_50
    "antarctica" -> Res.drawable.flag_antarctica_50
    "antigua_and_barbuda" -> Res.drawable.flag_antigua_and_barbuda_50
    "argentina" -> Res.drawable.flag_argentina_50
    "armenia" -> Res.drawable.flag_armenia_50
    "aruba" -> Res.drawable.flag_aruba_50
    "australia" -> Res.drawable.flag_australia_50
    "austria" -> Res.drawable.flag_austria_50
    "azerbaijan" -> Res.drawable.flag_azerbaijan_50
    "bahamas" -> Res.drawable.flag_bahamas_50
    "bahrain" -> Res.drawable.flag_bahrain_50
    "bangladesh" -> Res.drawable.flag_bangladesh_50
    "barbados" -> Res.drawable.flag_barbados_50
    "belarus" -> Res.drawable.flag_belarus_50
    "belgium" -> Res.drawable.flag_belgium_50
    "belize" -> Res.drawable.flag_belize_50
    "benin" -> Res.drawable.flag_benin_50
    "bermuda" -> Res.drawable.flag_bermuda_50
    "bhutan" -> Res.drawable.flag_bhutan_50
    "bolivia" -> Res.drawable.flag_bolivia_50
    "bosnia_and_herzegovina" -> Res.drawable.flag_bosnia_and_herzegovina_50
    "botswana" -> Res.drawable.flag_botswana_50
    "brazil" -> Res.drawable.flag_brazil_50
    "british_indian_ocean_territory" -> Res.drawable.flag_british_indian_ocean_territory_50
    "british_virgin_islands" -> Res.drawable.flag_british_virgin_islands_50
    "brunei_darussalam" -> Res.drawable.flag_brunei_darussalam_50
    "bulgaria" -> Res.drawable.flag_bulgaria_50
    "burkina_faso" -> Res.drawable.flag_burkina_faso_50
    "burundi" -> Res.drawable.flag_burundi_50
    "cambodia" -> Res.drawable.flag_cambodia_50
    "cameroon" -> Res.drawable.flag_cameroon_50
    "canada" -> Res.drawable.flag_canada_50
    "cape_verde" -> Res.drawable.flag_cape_verde_50
    "catalonia_flag" -> Res.drawable.flag_catalonia_flag_50
    "cayman_islands" -> Res.drawable.flag_cayman_islands_50
    "central_african_republic" -> Res.drawable.flag_central_african_republic_50
    "chad" -> Res.drawable.flag_chad_50
    "chile" -> Res.drawable.flag_chile_50
    "china" -> Res.drawable.flag_china_50
    "christmas_island" -> Res.drawable.flag_christmas_island_50
    "cocos_keeling_islands" -> Res.drawable.flag_cocos_keeling_islands_50
    "colombia" -> Res.drawable.flag_colombia_50
    "comoros" -> Res.drawable.flag_comoros_50
    "congo" -> Res.drawable.flag_congo_50
    "cook_islands" -> Res.drawable.flag_cook_islands_50
    "costa_rica" -> Res.drawable.flag_costa_rica_50
    "croatia" -> Res.drawable.flag_croatia_50
    "cuba" -> Res.drawable.flag_cuba_50
    "curacao" -> Res.drawable.flag_curacao_50
    "cyprus" -> Res.drawable.flag_cyprus_50
    "czech_republic" -> Res.drawable.flag_czech_republic_50
    "democratic_republic_of_the_congo" -> Res.drawable.flag_democratic_republic_of_the_congo_50
    "denmark" -> Res.drawable.flag_denmark_50
    "djibouti" -> Res.drawable.flag_djibouti_50
    "dominica" -> Res.drawable.flag_dominica_50
    "dominican_republic" -> Res.drawable.flag_dominican_republic_50
    "ecuador" -> Res.drawable.flag_ecuador_50
    "egypt" -> Res.drawable.flag_egypt_50
    "el_salvador" -> Res.drawable.flag_el_salvador_50
    "england" -> Res.drawable.flag_england_50
    "equatorial_guinea" -> Res.drawable.flag_equatorial_guinea_50
    "eritrea" -> Res.drawable.flag_eritrea_50
    "esperanto_flag" -> Res.drawable.flag_esperanto_flag_50
    "estonia" -> Res.drawable.flag_estonia_50
    "eswatini" -> Res.drawable.flag_eswatini_50
    "ethiopia" -> Res.drawable.flag_ethiopia_50
    "falkland_islands" -> Res.drawable.flag_falkland_islands_50
    "faroe_islands" -> Res.drawable.flag_faroe_islands_50
    "fiji" -> Res.drawable.flag_fiji_50
    "finland" -> Res.drawable.flag_finland_50
    "france" -> Res.drawable.flag_france_50
    "french_polynesia" -> Res.drawable.flag_french_polynesia_50
    "french_southern_territories" -> Res.drawable.flag_french_southern_territories_50
    "gabon" -> Res.drawable.flag_gabon_50
    "gambia" -> Res.drawable.flag_gambia_50
    "georgia" -> Res.drawable.flag_georgia_50
    "germany" -> Res.drawable.flag_germany_50
    "ghana" -> Res.drawable.flag_ghana_50
    "gibraltar" -> Res.drawable.flag_gibraltar_50
    "great_britain" -> Res.drawable.flag_great_britain_50
    "greece" -> Res.drawable.flag_greece_50
    "greenland" -> Res.drawable.flag_greenland_50
    "grenada" -> Res.drawable.flag_grenada_50
    "guam" -> Res.drawable.flag_guam_50
    "guatemala" -> Res.drawable.flag_guatemala_50
    "guernsey" -> Res.drawable.flag_guernsey_50
    "guinea" -> Res.drawable.flag_guinea_50
    "guinea_bissau" -> Res.drawable.flag_guinea_bissau_50
    "guyana" -> Res.drawable.flag_guyana_50
    "haiti" -> Res.drawable.flag_haiti_50
    "honduras" -> Res.drawable.flag_honduras_50
    "hong_kong" -> Res.drawable.flag_hong_kong_50
    "hungary" -> Res.drawable.flag_hungary_50
    "iceland" -> Res.drawable.flag_iceland_50
    "india" -> Res.drawable.flag_india_50
    "indonesia" -> Res.drawable.flag_indonesia_50
    "iran" -> Res.drawable.flag_iran_50
    "iraq" -> Res.drawable.flag_iraq_50
    "ireland" -> Res.drawable.flag_ireland_50
    "isle_of_man" -> Res.drawable.flag_isle_of_man_50
    "israel" -> Res.drawable.flag_israel_50
    "italy" -> Res.drawable.flag_italy_50
    "ivory_coast" -> Res.drawable.flag_ivory_coast_50
    "jamaica" -> Res.drawable.flag_jamaica_50
    "japan" -> Res.drawable.flag_japan_50
    "jersey" -> Res.drawable.flag_jersey_50
    "jordan" -> Res.drawable.flag_jordan_50
    "kazakhstan" -> Res.drawable.flag_kazakhstan_50
    "kenya" -> Res.drawable.flag_kenya_50
    "kiribati" -> Res.drawable.flag_kiribati_50
    "kuwait" -> Res.drawable.flag_kuwait_50
    "kyrgyzstan" -> Res.drawable.flag_kyrgyzstan_50
    "laos" -> Res.drawable.flag_laos_50
    "latvia" -> Res.drawable.flag_latvia_50
    "lebanon" -> Res.drawable.flag_lebanon_50
    "lesotho" -> Res.drawable.flag_lesotho_50
    "liberia" -> Res.drawable.flag_liberia_50
    "libya" -> Res.drawable.flag_libya_50
    "liechtenstein" -> Res.drawable.flag_liechtenstein_50
    "lithuania" -> Res.drawable.flag_lithuania_50
    "luxembourg" -> Res.drawable.flag_luxembourg_50
    "macao" -> Res.drawable.flag_macao_50
    "macedonia" -> Res.drawable.flag_macedonia_50
    "madagascar" -> Res.drawable.flag_madagascar_50
    "malawi" -> Res.drawable.flag_malawi_50
    "malaysia" -> Res.drawable.flag_malaysia_50
    "maldives" -> Res.drawable.flag_maldives_50
    "mali" -> Res.drawable.flag_mali_50
    "malta" -> Res.drawable.flag_malta_50
    "marshall_islands" -> Res.drawable.flag_marshall_islands_50
    "mauritania" -> Res.drawable.flag_mauritania_50
    "mauritius" -> Res.drawable.flag_mauritius_50
    "mexico" -> Res.drawable.flag_mexico_50
    "micronesia" -> Res.drawable.flag_micronesia_50
    "moldova" -> Res.drawable.flag_moldova_50
    "monaco" -> Res.drawable.flag_monaco_50
    "mongolia" -> Res.drawable.flag_mongolia_50
    "montenegro" -> Res.drawable.flag_montenegro_50
    "montserrat" -> Res.drawable.flag_montserrat_50
    "morocco" -> Res.drawable.flag_morocco_50
    "mozambique" -> Res.drawable.flag_mozambique_50
    "myanmar" -> Res.drawable.flag_myanmar_50
    "namibia" -> Res.drawable.flag_namibia_50
    "nauru" -> Res.drawable.flag_nauru_50
    "nepal" -> Res.drawable.flag_nepal_50
    "netherlands" -> Res.drawable.flag_netherlands_50
    "new_zealand" -> Res.drawable.flag_new_zealand_50
    "nicaragua" -> Res.drawable.flag_nicaragua_50
    "niger" -> Res.drawable.flag_niger_50
    "nigeria" -> Res.drawable.flag_nigeria_50
    "niue" -> Res.drawable.flag_niue_50
    "norfolk_island" -> Res.drawable.flag_norfolk_island_50
    "north_korea" -> Res.drawable.flag_north_korea_50
    "northern_mariana_islands" -> Res.drawable.flag_northern_mariana_islands_50
    "norway" -> Res.drawable.flag_norway_50
    "oman" -> Res.drawable.flag_oman_50
    "pakistan" -> Res.drawable.flag_pakistan_50
    "panama" -> Res.drawable.flag_panama_50
    "papua_new_guinea" -> Res.drawable.flag_papua_new_guinea_50
    "paraguay" -> Res.drawable.flag_paraguay_50
    "peru" -> Res.drawable.flag_peru_50
    "philippines" -> Res.drawable.flag_philippines_50
    "pitcairn_islands" -> Res.drawable.flag_pitcairn_islands_50
    "poland" -> Res.drawable.flag_poland_50
    "portugal" -> Res.drawable.flag_portugal_50
    "puerto_rico" -> Res.drawable.flag_puerto_rico_50
    "qatar" -> Res.drawable.flag_qatar_50
    "romania" -> Res.drawable.flag_romania_50
    "russian_federation" -> Res.drawable.flag_russian_federation_50
    "rwanda" -> Res.drawable.flag_rwanda_50
    "saint_kitts_and_nevis" -> Res.drawable.flag_saint_kitts_and_nevis_50
    "saint_lucia" -> Res.drawable.flag_saint_lucia_50
    "saint_vincent_and_the_grenadines" -> Res.drawable.flag_saint_vincent_and_the_grenadines_50
    "samoa" -> Res.drawable.flag_samoa_50
    "san_marino" -> Res.drawable.flag_san_marino_50
    "sao_tome_and_principe" -> Res.drawable.flag_sao_tome_and_principe_50
    "saudi_arabia" -> Res.drawable.flag_saudi_arabia_50
    "scotland" -> Res.drawable.flag_scotland_50
    "senegal" -> Res.drawable.flag_senegal_50
    "serbia" -> Res.drawable.flag_serbia_50
    "seychelles" -> Res.drawable.flag_seychelles_50
    "sierra_leone" -> Res.drawable.flag_sierra_leone_50
    "singapore" -> Res.drawable.flag_singapore_50
    "slovakia" -> Res.drawable.flag_slovakia_50
    "slovenia" -> Res.drawable.flag_slovenia_50
    "solomon_islands" -> Res.drawable.flag_solomon_islands_50
    "somalia" -> Res.drawable.flag_somalia_50
    "south_africa" -> Res.drawable.flag_south_africa_50
    "south_georgia_and_the_south_sandwich_islands" -> Res.drawable.flag_south_georgia_and_the_south_sandwich_islands_50
    "south_korea" -> Res.drawable.flag_south_korea_50
    "south_sudan" -> Res.drawable.flag_south_sudan_50
    "spain" -> Res.drawable.flag_spain_50
    "sri_lanka" -> Res.drawable.flag_sri_lanka_50
    "sudan" -> Res.drawable.flag_sudan_50
    "suriname" -> Res.drawable.flag_suriname_50
    "sweden" -> Res.drawable.flag_sweden_50
    "switzerland" -> Res.drawable.flag_switzerland_50
    "syria" -> Res.drawable.flag_syria_50
    "tajikistan" -> Res.drawable.flag_tajikistan_50
    "tanzania" -> Res.drawable.flag_tanzania_50
    "thailand" -> Res.drawable.flag_thailand_50
    "timor_leste" -> Res.drawable.flag_timor_leste_50
    "togo" -> Res.drawable.flag_togo_50
    "tokelau" -> Res.drawable.flag_tokelau_50
    "tonga" -> Res.drawable.flag_tonga_50
    "trinidad_and_tobago" -> Res.drawable.flag_trinidad_and_tobago_50
    "tunisia" -> Res.drawable.flag_tunisia_50
    "turkey" -> Res.drawable.flag_turkey_50
    "turkmenistan" -> Res.drawable.flag_turkmenistan_50
    "turks_and_caicos_islands" -> Res.drawable.flag_turks_and_caicos_islands_50
    "tuvalu" -> Res.drawable.flag_tuvalu_50
    "uganda" -> Res.drawable.flag_uganda_50
    "ukraine" -> Res.drawable.flag_ukraine_50
    "united_arab_emirates" -> Res.drawable.flag_united_arab_emirates_50
    "united_states_virgin_islands" -> Res.drawable.flag_united_states_virgin_islands_50
    "uruguay" -> Res.drawable.flag_uruguay_50
    "usa" -> Res.drawable.flag_usa_50
    "ussr" -> Res.drawable.flag_ussr_50
    "uzbekistan" -> Res.drawable.flag_uzbekistan_50
    "vanuatu" -> Res.drawable.flag_vanuatu_50
    "vatican_city" -> Res.drawable.flag_vatican_city_50
    "venezuela" -> Res.drawable.flag_venezuela_50
    "vietnam" -> Res.drawable.flag_vietnam_50
    "western_sahara" -> Res.drawable.flag_western_sahara_50
    "yemen" -> Res.drawable.flag_yemen_50
    "zambia" -> Res.drawable.flag_zambia_50
    "zimbabwe" -> Res.drawable.flag_zimbabwe_50
    else -> Res.drawable.flag_argentina_50 // fallback, should not happen
}

fun countryNameRes(slug: String): StringResource = when (slug) {
    "afghanistan" -> Res.string.country_afghanistan
    "aland_islands" -> Res.string.country_aland_islands
    "albania" -> Res.string.country_albania
    "algeria" -> Res.string.country_algeria
    "andorra" -> Res.string.country_andorra
    "angola" -> Res.string.country_angola
    "anguilla" -> Res.string.country_anguilla
    "antarctica" -> Res.string.country_antarctica
    "antigua_and_barbuda" -> Res.string.country_antigua_and_barbuda
    "argentina" -> Res.string.country_argentina
    "armenia" -> Res.string.country_armenia
    "aruba" -> Res.string.country_aruba
    "australia" -> Res.string.country_australia
    "austria" -> Res.string.country_austria
    "azerbaijan" -> Res.string.country_azerbaijan
    "bahamas" -> Res.string.country_bahamas
    "bahrain" -> Res.string.country_bahrain
    "bangladesh" -> Res.string.country_bangladesh
    "barbados" -> Res.string.country_barbados
    "belarus" -> Res.string.country_belarus
    "belgium" -> Res.string.country_belgium
    "belize" -> Res.string.country_belize
    "benin" -> Res.string.country_benin
    "bermuda" -> Res.string.country_bermuda
    "bhutan" -> Res.string.country_bhutan
    "bolivia" -> Res.string.country_bolivia
    "bosnia_and_herzegovina" -> Res.string.country_bosnia_and_herzegovina
    "botswana" -> Res.string.country_botswana
    "brazil" -> Res.string.country_brazil
    "british_indian_ocean_territory" -> Res.string.country_british_indian_ocean_territory
    "british_virgin_islands" -> Res.string.country_british_virgin_islands
    "brunei_darussalam" -> Res.string.country_brunei_darussalam
    "bulgaria" -> Res.string.country_bulgaria
    "burkina_faso" -> Res.string.country_burkina_faso
    "burundi" -> Res.string.country_burundi
    "cambodia" -> Res.string.country_cambodia
    "cameroon" -> Res.string.country_cameroon
    "canada" -> Res.string.country_canada
    "cape_verde" -> Res.string.country_cape_verde
    "catalonia_flag" -> Res.string.country_catalonia_flag
    "cayman_islands" -> Res.string.country_cayman_islands
    "central_african_republic" -> Res.string.country_central_african_republic
    "chad" -> Res.string.country_chad
    "chile" -> Res.string.country_chile
    "china" -> Res.string.country_china
    "christmas_island" -> Res.string.country_christmas_island
    "cocos_keeling_islands" -> Res.string.country_cocos_keeling_islands
    "colombia" -> Res.string.country_colombia
    "comoros" -> Res.string.country_comoros
    "congo" -> Res.string.country_congo
    "cook_islands" -> Res.string.country_cook_islands
    "costa_rica" -> Res.string.country_costa_rica
    "croatia" -> Res.string.country_croatia
    "cuba" -> Res.string.country_cuba
    "curacao" -> Res.string.country_curacao
    "cyprus" -> Res.string.country_cyprus
    "czech_republic" -> Res.string.country_czech_republic
    "democratic_republic_of_the_congo" -> Res.string.country_democratic_republic_of_the_congo
    "denmark" -> Res.string.country_denmark
    "djibouti" -> Res.string.country_djibouti
    "dominica" -> Res.string.country_dominica
    "dominican_republic" -> Res.string.country_dominican_republic
    "ecuador" -> Res.string.country_ecuador
    "egypt" -> Res.string.country_egypt
    "el_salvador" -> Res.string.country_el_salvador
    "england" -> Res.string.country_england
    "equatorial_guinea" -> Res.string.country_equatorial_guinea
    "eritrea" -> Res.string.country_eritrea
    "esperanto_flag" -> Res.string.country_esperanto_flag
    "estonia" -> Res.string.country_estonia
    "eswatini" -> Res.string.country_eswatini
    "ethiopia" -> Res.string.country_ethiopia
    "falkland_islands" -> Res.string.country_falkland_islands
    "faroe_islands" -> Res.string.country_faroe_islands
    "fiji" -> Res.string.country_fiji
    "finland" -> Res.string.country_finland
    "france" -> Res.string.country_france
    "french_polynesia" -> Res.string.country_french_polynesia
    "french_southern_territories" -> Res.string.country_french_southern_territories
    "gabon" -> Res.string.country_gabon
    "gambia" -> Res.string.country_gambia
    "georgia" -> Res.string.country_georgia
    "germany" -> Res.string.country_germany
    "ghana" -> Res.string.country_ghana
    "gibraltar" -> Res.string.country_gibraltar
    "great_britain" -> Res.string.country_great_britain
    "greece" -> Res.string.country_greece
    "greenland" -> Res.string.country_greenland
    "grenada" -> Res.string.country_grenada
    "guam" -> Res.string.country_guam
    "guatemala" -> Res.string.country_guatemala
    "guernsey" -> Res.string.country_guernsey
    "guinea" -> Res.string.country_guinea
    "guinea_bissau" -> Res.string.country_guinea_bissau
    "guyana" -> Res.string.country_guyana
    "haiti" -> Res.string.country_haiti
    "honduras" -> Res.string.country_honduras
    "hong_kong" -> Res.string.country_hong_kong
    "hungary" -> Res.string.country_hungary
    "iceland" -> Res.string.country_iceland
    "india" -> Res.string.country_india
    "indonesia" -> Res.string.country_indonesia
    "iran" -> Res.string.country_iran
    "iraq" -> Res.string.country_iraq
    "ireland" -> Res.string.country_ireland
    "isle_of_man" -> Res.string.country_isle_of_man
    "israel" -> Res.string.country_israel
    "italy" -> Res.string.country_italy
    "ivory_coast" -> Res.string.country_ivory_coast
    "jamaica" -> Res.string.country_jamaica
    "japan" -> Res.string.country_japan
    "jersey" -> Res.string.country_jersey
    "jordan" -> Res.string.country_jordan
    "kazakhstan" -> Res.string.country_kazakhstan
    "kenya" -> Res.string.country_kenya
    "kiribati" -> Res.string.country_kiribati
    "kuwait" -> Res.string.country_kuwait
    "kyrgyzstan" -> Res.string.country_kyrgyzstan
    "laos" -> Res.string.country_laos
    "latvia" -> Res.string.country_latvia
    "lebanon" -> Res.string.country_lebanon
    "lesotho" -> Res.string.country_lesotho
    "liberia" -> Res.string.country_liberia
    "libya" -> Res.string.country_libya
    "liechtenstein" -> Res.string.country_liechtenstein
    "lithuania" -> Res.string.country_lithuania
    "luxembourg" -> Res.string.country_luxembourg
    "macao" -> Res.string.country_macao
    "macedonia" -> Res.string.country_macedonia
    "madagascar" -> Res.string.country_madagascar
    "malawi" -> Res.string.country_malawi
    "malaysia" -> Res.string.country_malaysia
    "maldives" -> Res.string.country_maldives
    "mali" -> Res.string.country_mali
    "malta" -> Res.string.country_malta
    "marshall_islands" -> Res.string.country_marshall_islands
    "mauritania" -> Res.string.country_mauritania
    "mauritius" -> Res.string.country_mauritius
    "mexico" -> Res.string.country_mexico
    "micronesia" -> Res.string.country_micronesia
    "moldova" -> Res.string.country_moldova
    "monaco" -> Res.string.country_monaco
    "mongolia" -> Res.string.country_mongolia
    "montenegro" -> Res.string.country_montenegro
    "montserrat" -> Res.string.country_montserrat
    "morocco" -> Res.string.country_morocco
    "mozambique" -> Res.string.country_mozambique
    "myanmar" -> Res.string.country_myanmar
    "namibia" -> Res.string.country_namibia
    "nauru" -> Res.string.country_nauru
    "nepal" -> Res.string.country_nepal
    "netherlands" -> Res.string.country_netherlands
    "new_zealand" -> Res.string.country_new_zealand
    "nicaragua" -> Res.string.country_nicaragua
    "niger" -> Res.string.country_niger
    "nigeria" -> Res.string.country_nigeria
    "niue" -> Res.string.country_niue
    "norfolk_island" -> Res.string.country_norfolk_island
    "north_korea" -> Res.string.country_north_korea
    "northern_mariana_islands" -> Res.string.country_northern_mariana_islands
    "norway" -> Res.string.country_norway
    "oman" -> Res.string.country_oman
    "pakistan" -> Res.string.country_pakistan
    "panama" -> Res.string.country_panama
    "papua_new_guinea" -> Res.string.country_papua_new_guinea
    "paraguay" -> Res.string.country_paraguay
    "peru" -> Res.string.country_peru
    "philippines" -> Res.string.country_philippines
    "pitcairn_islands" -> Res.string.country_pitcairn_islands
    "poland" -> Res.string.country_poland
    "portugal" -> Res.string.country_portugal
    "puerto_rico" -> Res.string.country_puerto_rico
    "qatar" -> Res.string.country_qatar
    "romania" -> Res.string.country_romania
    "russian_federation" -> Res.string.country_russian_federation
    "rwanda" -> Res.string.country_rwanda
    "saint_kitts_and_nevis" -> Res.string.country_saint_kitts_and_nevis
    "saint_lucia" -> Res.string.country_saint_lucia
    "saint_vincent_and_the_grenadines" -> Res.string.country_saint_vincent_and_the_grenadines
    "samoa" -> Res.string.country_samoa
    "san_marino" -> Res.string.country_san_marino
    "sao_tome_and_principe" -> Res.string.country_sao_tome_and_principe
    "saudi_arabia" -> Res.string.country_saudi_arabia
    "scotland" -> Res.string.country_scotland
    "senegal" -> Res.string.country_senegal
    "serbia" -> Res.string.country_serbia
    "seychelles" -> Res.string.country_seychelles
    "sierra_leone" -> Res.string.country_sierra_leone
    "singapore" -> Res.string.country_singapore
    "slovakia" -> Res.string.country_slovakia
    "slovenia" -> Res.string.country_slovenia
    "solomon_islands" -> Res.string.country_solomon_islands
    "somalia" -> Res.string.country_somalia
    "south_africa" -> Res.string.country_south_africa
    "south_georgia_and_the_south_sandwich_islands" -> Res.string.country_south_georgia_and_the_south_sandwich_islands
    "south_korea" -> Res.string.country_south_korea
    "south_sudan" -> Res.string.country_south_sudan
    "spain" -> Res.string.country_spain
    "sri_lanka" -> Res.string.country_sri_lanka
    "sudan" -> Res.string.country_sudan
    "suriname" -> Res.string.country_suriname
    "sweden" -> Res.string.country_sweden
    "switzerland" -> Res.string.country_switzerland
    "syria" -> Res.string.country_syria
    "tajikistan" -> Res.string.country_tajikistan
    "tanzania" -> Res.string.country_tanzania
    "thailand" -> Res.string.country_thailand
    "timor_leste" -> Res.string.country_timor_leste
    "togo" -> Res.string.country_togo
    "tokelau" -> Res.string.country_tokelau
    "tonga" -> Res.string.country_tonga
    "trinidad_and_tobago" -> Res.string.country_trinidad_and_tobago
    "tunisia" -> Res.string.country_tunisia
    "turkey" -> Res.string.country_turkey
    "turkmenistan" -> Res.string.country_turkmenistan
    "turks_and_caicos_islands" -> Res.string.country_turks_and_caicos_islands
    "tuvalu" -> Res.string.country_tuvalu
    "uganda" -> Res.string.country_uganda
    "ukraine" -> Res.string.country_ukraine
    "united_arab_emirates" -> Res.string.country_united_arab_emirates
    "united_states_virgin_islands" -> Res.string.country_united_states_virgin_islands
    "uruguay" -> Res.string.country_uruguay
    "usa" -> Res.string.country_usa
    "ussr" -> Res.string.country_ussr
    "uzbekistan" -> Res.string.country_uzbekistan
    "vanuatu" -> Res.string.country_vanuatu
    "vatican_city" -> Res.string.country_vatican_city
    "venezuela" -> Res.string.country_venezuela
    "vietnam" -> Res.string.country_vietnam
    "western_sahara" -> Res.string.country_western_sahara
    "yemen" -> Res.string.country_yemen
    "zambia" -> Res.string.country_zambia
    "zimbabwe" -> Res.string.country_zimbabwe
    else -> Res.string.country_argentina // fallback
}
