package com.inspiredandroid.braincup.ui.screens

import braincup.composeapp.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource

fun flagResource(slug: String): DrawableResource = when (slug) {
    "afghanistan" -> Res.drawable.flag_afghanistan
    "aland_islands" -> Res.drawable.flag_aland_islands
    "albania" -> Res.drawable.flag_albania
    "algeria" -> Res.drawable.flag_algeria
    "andorra" -> Res.drawable.flag_andorra
    "angola" -> Res.drawable.flag_angola
    "anguilla" -> Res.drawable.flag_anguilla
    "antarctica" -> Res.drawable.flag_antarctica
    "antigua_and_barbuda" -> Res.drawable.flag_antigua_and_barbuda
    "argentina" -> Res.drawable.flag_argentina
    "armenia" -> Res.drawable.flag_armenia
    "aruba" -> Res.drawable.flag_aruba
    "australia" -> Res.drawable.flag_australia
    "austria" -> Res.drawable.flag_austria
    "azerbaijan" -> Res.drawable.flag_azerbaijan
    "bahamas" -> Res.drawable.flag_bahamas
    "bahrain" -> Res.drawable.flag_bahrain
    "bangladesh" -> Res.drawable.flag_bangladesh
    "barbados" -> Res.drawable.flag_barbados
    "belarus" -> Res.drawable.flag_belarus
    "belgium" -> Res.drawable.flag_belgium
    "belize" -> Res.drawable.flag_belize
    "benin" -> Res.drawable.flag_benin
    "bermuda" -> Res.drawable.flag_bermuda
    "bhutan" -> Res.drawable.flag_bhutan
    "bolivia" -> Res.drawable.flag_bolivia
    "bosnia_and_herzegovina" -> Res.drawable.flag_bosnia_and_herzegovina
    "botswana" -> Res.drawable.flag_botswana
    "brazil" -> Res.drawable.flag_brazil
    "british_indian_ocean_territory" -> Res.drawable.flag_british_indian_ocean_territory
    "british_virgin_islands" -> Res.drawable.flag_british_virgin_islands
    "brunei_darussalam" -> Res.drawable.flag_brunei_darussalam
    "bulgaria" -> Res.drawable.flag_bulgaria
    "burkina_faso" -> Res.drawable.flag_burkina_faso
    "burundi" -> Res.drawable.flag_burundi
    "cambodia" -> Res.drawable.flag_cambodia
    "cameroon" -> Res.drawable.flag_cameroon
    "canada" -> Res.drawable.flag_canada
    "cape_verde" -> Res.drawable.flag_cape_verde
    "catalonia_flag" -> Res.drawable.flag_catalonia_flag
    "cayman_islands" -> Res.drawable.flag_cayman_islands
    "central_african_republic" -> Res.drawable.flag_central_african_republic
    "chad" -> Res.drawable.flag_chad
    "chile" -> Res.drawable.flag_chile
    "china" -> Res.drawable.flag_china
    "christmas_island" -> Res.drawable.flag_christmas_island
    "cocos_keeling_islands" -> Res.drawable.flag_cocos_keeling_islands
    "colombia" -> Res.drawable.flag_colombia
    "comoros" -> Res.drawable.flag_comoros
    "congo" -> Res.drawable.flag_congo
    "cook_islands" -> Res.drawable.flag_cook_islands
    "costa_rica" -> Res.drawable.flag_costa_rica
    "croatia" -> Res.drawable.flag_croatia
    "cuba" -> Res.drawable.flag_cuba
    "curacao" -> Res.drawable.flag_curacao
    "cyprus" -> Res.drawable.flag_cyprus
    "czech_republic" -> Res.drawable.flag_czech_republic
    "democratic_republic_of_the_congo" -> Res.drawable.flag_democratic_republic_of_the_congo
    "denmark" -> Res.drawable.flag_denmark
    "djibouti" -> Res.drawable.flag_djibouti
    "dominica" -> Res.drawable.flag_dominica
    "dominican_republic" -> Res.drawable.flag_dominican_republic
    "ecuador" -> Res.drawable.flag_ecuador
    "egypt" -> Res.drawable.flag_egypt
    "el_salvador" -> Res.drawable.flag_el_salvador
    "england" -> Res.drawable.flag_england
    "equatorial_guinea" -> Res.drawable.flag_equatorial_guinea
    "eritrea" -> Res.drawable.flag_eritrea
    "estonia" -> Res.drawable.flag_estonia
    "eswatini" -> Res.drawable.flag_eswatini
    "ethiopia" -> Res.drawable.flag_ethiopia
    "falkland_islands" -> Res.drawable.flag_falkland_islands
    "faroe_islands" -> Res.drawable.flag_faroe_islands
    "fiji" -> Res.drawable.flag_fiji
    "finland" -> Res.drawable.flag_finland
    "france" -> Res.drawable.flag_france
    "french_polynesia" -> Res.drawable.flag_french_polynesia
    "french_southern_territories" -> Res.drawable.flag_french_southern_territories
    "gabon" -> Res.drawable.flag_gabon
    "gambia" -> Res.drawable.flag_gambia
    "georgia" -> Res.drawable.flag_georgia
    "germany" -> Res.drawable.flag_germany
    "ghana" -> Res.drawable.flag_ghana
    "gibraltar" -> Res.drawable.flag_gibraltar
    "great_britain" -> Res.drawable.flag_great_britain
    "greece" -> Res.drawable.flag_greece
    "greenland" -> Res.drawable.flag_greenland
    "grenada" -> Res.drawable.flag_grenada
    "guam" -> Res.drawable.flag_guam
    "guatemala" -> Res.drawable.flag_guatemala
    "guernsey" -> Res.drawable.flag_guernsey
    "guinea" -> Res.drawable.flag_guinea
    "guinea_bissau" -> Res.drawable.flag_guinea_bissau
    "guyana" -> Res.drawable.flag_guyana
    "haiti" -> Res.drawable.flag_haiti
    "honduras" -> Res.drawable.flag_honduras
    "hong_kong" -> Res.drawable.flag_hong_kong
    "hungary" -> Res.drawable.flag_hungary
    "iceland" -> Res.drawable.flag_iceland
    "india" -> Res.drawable.flag_india
    "indonesia" -> Res.drawable.flag_indonesia
    "iran" -> Res.drawable.flag_iran
    "iraq" -> Res.drawable.flag_iraq
    "ireland" -> Res.drawable.flag_ireland
    "isle_of_man" -> Res.drawable.flag_isle_of_man
    "israel" -> Res.drawable.flag_israel
    "italy" -> Res.drawable.flag_italy
    "ivory_coast" -> Res.drawable.flag_ivory_coast
    "jamaica" -> Res.drawable.flag_jamaica
    "japan" -> Res.drawable.flag_japan
    "jersey" -> Res.drawable.flag_jersey
    "jordan" -> Res.drawable.flag_jordan
    "kazakhstan" -> Res.drawable.flag_kazakhstan
    "kenya" -> Res.drawable.flag_kenya
    "kiribati" -> Res.drawable.flag_kiribati
    "kuwait" -> Res.drawable.flag_kuwait
    "kyrgyzstan" -> Res.drawable.flag_kyrgyzstan
    "laos" -> Res.drawable.flag_laos
    "latvia" -> Res.drawable.flag_latvia
    "lebanon" -> Res.drawable.flag_lebanon
    "lesotho" -> Res.drawable.flag_lesotho
    "liberia" -> Res.drawable.flag_liberia
    "libya" -> Res.drawable.flag_libya
    "liechtenstein" -> Res.drawable.flag_liechtenstein
    "lithuania" -> Res.drawable.flag_lithuania
    "luxembourg" -> Res.drawable.flag_luxembourg
    "macao" -> Res.drawable.flag_macao
    "macedonia" -> Res.drawable.flag_macedonia
    "madagascar" -> Res.drawable.flag_madagascar
    "malawi" -> Res.drawable.flag_malawi
    "malaysia" -> Res.drawable.flag_malaysia
    "maldives" -> Res.drawable.flag_maldives
    "mali" -> Res.drawable.flag_mali
    "malta" -> Res.drawable.flag_malta
    "marshall_islands" -> Res.drawable.flag_marshall_islands
    "mauritania" -> Res.drawable.flag_mauritania
    "mauritius" -> Res.drawable.flag_mauritius
    "mexico" -> Res.drawable.flag_mexico
    "micronesia" -> Res.drawable.flag_micronesia
    "moldova" -> Res.drawable.flag_moldova
    "monaco" -> Res.drawable.flag_monaco
    "mongolia" -> Res.drawable.flag_mongolia
    "montenegro" -> Res.drawable.flag_montenegro
    "montserrat" -> Res.drawable.flag_montserrat
    "morocco" -> Res.drawable.flag_morocco
    "mozambique" -> Res.drawable.flag_mozambique
    "myanmar" -> Res.drawable.flag_myanmar
    "namibia" -> Res.drawable.flag_namibia
    "nauru" -> Res.drawable.flag_nauru
    "nepal" -> Res.drawable.flag_nepal
    "netherlands" -> Res.drawable.flag_netherlands
    "new_zealand" -> Res.drawable.flag_new_zealand
    "nicaragua" -> Res.drawable.flag_nicaragua
    "niger" -> Res.drawable.flag_niger
    "nigeria" -> Res.drawable.flag_nigeria
    "niue" -> Res.drawable.flag_niue
    "norfolk_island" -> Res.drawable.flag_norfolk_island
    "north_korea" -> Res.drawable.flag_north_korea
    "northern_mariana_islands" -> Res.drawable.flag_northern_mariana_islands
    "norway" -> Res.drawable.flag_norway
    "oman" -> Res.drawable.flag_oman
    "pakistan" -> Res.drawable.flag_pakistan
    "palestine" -> Res.drawable.flag_palestine
    "panama" -> Res.drawable.flag_panama
    "papua_new_guinea" -> Res.drawable.flag_papua_new_guinea
    "paraguay" -> Res.drawable.flag_paraguay
    "peru" -> Res.drawable.flag_peru
    "philippines" -> Res.drawable.flag_philippines
    "pitcairn_islands" -> Res.drawable.flag_pitcairn_islands
    "poland" -> Res.drawable.flag_poland
    "portugal" -> Res.drawable.flag_portugal
    "puerto_rico" -> Res.drawable.flag_puerto_rico
    "qatar" -> Res.drawable.flag_qatar
    "romania" -> Res.drawable.flag_romania
    "russian_federation" -> Res.drawable.flag_russian_federation
    "rwanda" -> Res.drawable.flag_rwanda
    "saint_kitts_and_nevis" -> Res.drawable.flag_saint_kitts_and_nevis
    "saint_lucia" -> Res.drawable.flag_saint_lucia
    "saint_vincent_and_the_grenadines" -> Res.drawable.flag_saint_vincent_and_the_grenadines
    "samoa" -> Res.drawable.flag_samoa
    "san_marino" -> Res.drawable.flag_san_marino
    "sao_tome_and_principe" -> Res.drawable.flag_sao_tome_and_principe
    "saudi_arabia" -> Res.drawable.flag_saudi_arabia
    "scotland" -> Res.drawable.flag_scotland
    "senegal" -> Res.drawable.flag_senegal
    "serbia" -> Res.drawable.flag_serbia
    "seychelles" -> Res.drawable.flag_seychelles
    "sierra_leone" -> Res.drawable.flag_sierra_leone
    "singapore" -> Res.drawable.flag_singapore
    "slovakia" -> Res.drawable.flag_slovakia
    "slovenia" -> Res.drawable.flag_slovenia
    "solomon_islands" -> Res.drawable.flag_solomon_islands
    "somalia" -> Res.drawable.flag_somalia
    "south_africa" -> Res.drawable.flag_south_africa
    "south_georgia_and_the_south_sandwich_islands" -> Res.drawable.flag_south_georgia_and_the_south_sandwich_islands
    "south_korea" -> Res.drawable.flag_south_korea
    "south_sudan" -> Res.drawable.flag_south_sudan
    "spain" -> Res.drawable.flag_spain
    "sri_lanka" -> Res.drawable.flag_sri_lanka
    "sudan" -> Res.drawable.flag_sudan
    "suriname" -> Res.drawable.flag_suriname
    "sweden" -> Res.drawable.flag_sweden
    "switzerland" -> Res.drawable.flag_switzerland
    "syria" -> Res.drawable.flag_syria
    "tajikistan" -> Res.drawable.flag_tajikistan
    "tanzania" -> Res.drawable.flag_tanzania
    "thailand" -> Res.drawable.flag_thailand
    "timor_leste" -> Res.drawable.flag_timor_leste
    "togo" -> Res.drawable.flag_togo
    "tokelau" -> Res.drawable.flag_tokelau
    "tonga" -> Res.drawable.flag_tonga
    "trinidad_and_tobago" -> Res.drawable.flag_trinidad_and_tobago
    "tunisia" -> Res.drawable.flag_tunisia
    "turkey" -> Res.drawable.flag_turkey
    "turkmenistan" -> Res.drawable.flag_turkmenistan
    "turks_and_caicos_islands" -> Res.drawable.flag_turks_and_caicos_islands
    "tuvalu" -> Res.drawable.flag_tuvalu
    "uganda" -> Res.drawable.flag_uganda
    "ukraine" -> Res.drawable.flag_ukraine
    "united_arab_emirates" -> Res.drawable.flag_united_arab_emirates
    "united_states_virgin_islands" -> Res.drawable.flag_united_states_virgin_islands
    "uruguay" -> Res.drawable.flag_uruguay
    "usa" -> Res.drawable.flag_usa
    "uzbekistan" -> Res.drawable.flag_uzbekistan
    "vanuatu" -> Res.drawable.flag_vanuatu
    "vatican_city" -> Res.drawable.flag_vatican_city
    "venezuela" -> Res.drawable.flag_venezuela
    "vietnam" -> Res.drawable.flag_vietnam
    "western_sahara" -> Res.drawable.flag_western_sahara
    "yemen" -> Res.drawable.flag_yemen
    "zambia" -> Res.drawable.flag_zambia
    "zimbabwe" -> Res.drawable.flag_zimbabwe
    else -> Res.drawable.flag_argentina // fallback, should not happen
}

fun countryNameRes(slug: String): StringResource = when (slug) {
    "afghanistan" -> Res.string.country_afghanistan
    "aland_islands" -> Res.string.country_aland_islands
    "albania" -> Res.string.country_albania
    "algeria" -> Res.string.country_algeria
    "andorra" -> Res.string.country_andorra
    "angola" -> Res.string.country_angola
    "anguilla" -> Res.string.country_anguilla
    "antarctica" -> Res.string.country_antarctica
    "antigua_and_barbuda" -> Res.string.country_antigua_and_barbuda
    "argentina" -> Res.string.country_argentina
    "armenia" -> Res.string.country_armenia
    "aruba" -> Res.string.country_aruba
    "australia" -> Res.string.country_australia
    "austria" -> Res.string.country_austria
    "azerbaijan" -> Res.string.country_azerbaijan
    "bahamas" -> Res.string.country_bahamas
    "bahrain" -> Res.string.country_bahrain
    "bangladesh" -> Res.string.country_bangladesh
    "barbados" -> Res.string.country_barbados
    "belarus" -> Res.string.country_belarus
    "belgium" -> Res.string.country_belgium
    "belize" -> Res.string.country_belize
    "benin" -> Res.string.country_benin
    "bermuda" -> Res.string.country_bermuda
    "bhutan" -> Res.string.country_bhutan
    "bolivia" -> Res.string.country_bolivia
    "bosnia_and_herzegovina" -> Res.string.country_bosnia_and_herzegovina
    "botswana" -> Res.string.country_botswana
    "brazil" -> Res.string.country_brazil
    "british_indian_ocean_territory" -> Res.string.country_british_indian_ocean_territory
    "british_virgin_islands" -> Res.string.country_british_virgin_islands
    "brunei_darussalam" -> Res.string.country_brunei_darussalam
    "bulgaria" -> Res.string.country_bulgaria
    "burkina_faso" -> Res.string.country_burkina_faso
    "burundi" -> Res.string.country_burundi
    "cambodia" -> Res.string.country_cambodia
    "cameroon" -> Res.string.country_cameroon
    "canada" -> Res.string.country_canada
    "cape_verde" -> Res.string.country_cape_verde
    "catalonia_flag" -> Res.string.country_catalonia_flag
    "cayman_islands" -> Res.string.country_cayman_islands
    "central_african_republic" -> Res.string.country_central_african_republic
    "chad" -> Res.string.country_chad
    "chile" -> Res.string.country_chile
    "china" -> Res.string.country_china
    "christmas_island" -> Res.string.country_christmas_island
    "cocos_keeling_islands" -> Res.string.country_cocos_keeling_islands
    "colombia" -> Res.string.country_colombia
    "comoros" -> Res.string.country_comoros
    "congo" -> Res.string.country_congo
    "cook_islands" -> Res.string.country_cook_islands
    "costa_rica" -> Res.string.country_costa_rica
    "croatia" -> Res.string.country_croatia
    "cuba" -> Res.string.country_cuba
    "curacao" -> Res.string.country_curacao
    "cyprus" -> Res.string.country_cyprus
    "czech_republic" -> Res.string.country_czech_republic
    "democratic_republic_of_the_congo" -> Res.string.country_democratic_republic_of_the_congo
    "denmark" -> Res.string.country_denmark
    "djibouti" -> Res.string.country_djibouti
    "dominica" -> Res.string.country_dominica
    "dominican_republic" -> Res.string.country_dominican_republic
    "ecuador" -> Res.string.country_ecuador
    "egypt" -> Res.string.country_egypt
    "el_salvador" -> Res.string.country_el_salvador
    "england" -> Res.string.country_england
    "equatorial_guinea" -> Res.string.country_equatorial_guinea
    "eritrea" -> Res.string.country_eritrea
    "estonia" -> Res.string.country_estonia
    "eswatini" -> Res.string.country_eswatini
    "ethiopia" -> Res.string.country_ethiopia
    "falkland_islands" -> Res.string.country_falkland_islands
    "faroe_islands" -> Res.string.country_faroe_islands
    "fiji" -> Res.string.country_fiji
    "finland" -> Res.string.country_finland
    "france" -> Res.string.country_france
    "french_polynesia" -> Res.string.country_french_polynesia
    "french_southern_territories" -> Res.string.country_french_southern_territories
    "gabon" -> Res.string.country_gabon
    "gambia" -> Res.string.country_gambia
    "georgia" -> Res.string.country_georgia
    "germany" -> Res.string.country_germany
    "ghana" -> Res.string.country_ghana
    "gibraltar" -> Res.string.country_gibraltar
    "great_britain" -> Res.string.country_great_britain
    "greece" -> Res.string.country_greece
    "greenland" -> Res.string.country_greenland
    "grenada" -> Res.string.country_grenada
    "guam" -> Res.string.country_guam
    "guatemala" -> Res.string.country_guatemala
    "guernsey" -> Res.string.country_guernsey
    "guinea" -> Res.string.country_guinea
    "guinea_bissau" -> Res.string.country_guinea_bissau
    "guyana" -> Res.string.country_guyana
    "haiti" -> Res.string.country_haiti
    "honduras" -> Res.string.country_honduras
    "hong_kong" -> Res.string.country_hong_kong
    "hungary" -> Res.string.country_hungary
    "iceland" -> Res.string.country_iceland
    "india" -> Res.string.country_india
    "indonesia" -> Res.string.country_indonesia
    "iran" -> Res.string.country_iran
    "iraq" -> Res.string.country_iraq
    "ireland" -> Res.string.country_ireland
    "isle_of_man" -> Res.string.country_isle_of_man
    "israel" -> Res.string.country_israel
    "italy" -> Res.string.country_italy
    "ivory_coast" -> Res.string.country_ivory_coast
    "jamaica" -> Res.string.country_jamaica
    "japan" -> Res.string.country_japan
    "jersey" -> Res.string.country_jersey
    "jordan" -> Res.string.country_jordan
    "kazakhstan" -> Res.string.country_kazakhstan
    "kenya" -> Res.string.country_kenya
    "kiribati" -> Res.string.country_kiribati
    "kuwait" -> Res.string.country_kuwait
    "kyrgyzstan" -> Res.string.country_kyrgyzstan
    "laos" -> Res.string.country_laos
    "latvia" -> Res.string.country_latvia
    "lebanon" -> Res.string.country_lebanon
    "lesotho" -> Res.string.country_lesotho
    "liberia" -> Res.string.country_liberia
    "libya" -> Res.string.country_libya
    "liechtenstein" -> Res.string.country_liechtenstein
    "lithuania" -> Res.string.country_lithuania
    "luxembourg" -> Res.string.country_luxembourg
    "macao" -> Res.string.country_macao
    "macedonia" -> Res.string.country_macedonia
    "madagascar" -> Res.string.country_madagascar
    "malawi" -> Res.string.country_malawi
    "malaysia" -> Res.string.country_malaysia
    "maldives" -> Res.string.country_maldives
    "mali" -> Res.string.country_mali
    "malta" -> Res.string.country_malta
    "marshall_islands" -> Res.string.country_marshall_islands
    "mauritania" -> Res.string.country_mauritania
    "mauritius" -> Res.string.country_mauritius
    "mexico" -> Res.string.country_mexico
    "micronesia" -> Res.string.country_micronesia
    "moldova" -> Res.string.country_moldova
    "monaco" -> Res.string.country_monaco
    "mongolia" -> Res.string.country_mongolia
    "montenegro" -> Res.string.country_montenegro
    "montserrat" -> Res.string.country_montserrat
    "morocco" -> Res.string.country_morocco
    "mozambique" -> Res.string.country_mozambique
    "myanmar" -> Res.string.country_myanmar
    "namibia" -> Res.string.country_namibia
    "nauru" -> Res.string.country_nauru
    "nepal" -> Res.string.country_nepal
    "netherlands" -> Res.string.country_netherlands
    "new_zealand" -> Res.string.country_new_zealand
    "nicaragua" -> Res.string.country_nicaragua
    "niger" -> Res.string.country_niger
    "nigeria" -> Res.string.country_nigeria
    "niue" -> Res.string.country_niue
    "norfolk_island" -> Res.string.country_norfolk_island
    "north_korea" -> Res.string.country_north_korea
    "northern_mariana_islands" -> Res.string.country_northern_mariana_islands
    "norway" -> Res.string.country_norway
    "oman" -> Res.string.country_oman
    "pakistan" -> Res.string.country_pakistan
    "palestine" -> Res.string.country_palestine
    "panama" -> Res.string.country_panama
    "papua_new_guinea" -> Res.string.country_papua_new_guinea
    "paraguay" -> Res.string.country_paraguay
    "peru" -> Res.string.country_peru
    "philippines" -> Res.string.country_philippines
    "pitcairn_islands" -> Res.string.country_pitcairn_islands
    "poland" -> Res.string.country_poland
    "portugal" -> Res.string.country_portugal
    "puerto_rico" -> Res.string.country_puerto_rico
    "qatar" -> Res.string.country_qatar
    "romania" -> Res.string.country_romania
    "russian_federation" -> Res.string.country_russian_federation
    "rwanda" -> Res.string.country_rwanda
    "saint_kitts_and_nevis" -> Res.string.country_saint_kitts_and_nevis
    "saint_lucia" -> Res.string.country_saint_lucia
    "saint_vincent_and_the_grenadines" -> Res.string.country_saint_vincent_and_the_grenadines
    "samoa" -> Res.string.country_samoa
    "san_marino" -> Res.string.country_san_marino
    "sao_tome_and_principe" -> Res.string.country_sao_tome_and_principe
    "saudi_arabia" -> Res.string.country_saudi_arabia
    "scotland" -> Res.string.country_scotland
    "senegal" -> Res.string.country_senegal
    "serbia" -> Res.string.country_serbia
    "seychelles" -> Res.string.country_seychelles
    "sierra_leone" -> Res.string.country_sierra_leone
    "singapore" -> Res.string.country_singapore
    "slovakia" -> Res.string.country_slovakia
    "slovenia" -> Res.string.country_slovenia
    "solomon_islands" -> Res.string.country_solomon_islands
    "somalia" -> Res.string.country_somalia
    "south_africa" -> Res.string.country_south_africa
    "south_georgia_and_the_south_sandwich_islands" -> Res.string.country_south_georgia_and_the_south_sandwich_islands
    "south_korea" -> Res.string.country_south_korea
    "south_sudan" -> Res.string.country_south_sudan
    "spain" -> Res.string.country_spain
    "sri_lanka" -> Res.string.country_sri_lanka
    "sudan" -> Res.string.country_sudan
    "suriname" -> Res.string.country_suriname
    "sweden" -> Res.string.country_sweden
    "switzerland" -> Res.string.country_switzerland
    "syria" -> Res.string.country_syria
    "tajikistan" -> Res.string.country_tajikistan
    "tanzania" -> Res.string.country_tanzania
    "thailand" -> Res.string.country_thailand
    "timor_leste" -> Res.string.country_timor_leste
    "togo" -> Res.string.country_togo
    "tokelau" -> Res.string.country_tokelau
    "tonga" -> Res.string.country_tonga
    "trinidad_and_tobago" -> Res.string.country_trinidad_and_tobago
    "tunisia" -> Res.string.country_tunisia
    "turkey" -> Res.string.country_turkey
    "turkmenistan" -> Res.string.country_turkmenistan
    "turks_and_caicos_islands" -> Res.string.country_turks_and_caicos_islands
    "tuvalu" -> Res.string.country_tuvalu
    "uganda" -> Res.string.country_uganda
    "ukraine" -> Res.string.country_ukraine
    "united_arab_emirates" -> Res.string.country_united_arab_emirates
    "united_states_virgin_islands" -> Res.string.country_united_states_virgin_islands
    "uruguay" -> Res.string.country_uruguay
    "usa" -> Res.string.country_usa
    "uzbekistan" -> Res.string.country_uzbekistan
    "vanuatu" -> Res.string.country_vanuatu
    "vatican_city" -> Res.string.country_vatican_city
    "venezuela" -> Res.string.country_venezuela
    "vietnam" -> Res.string.country_vietnam
    "western_sahara" -> Res.string.country_western_sahara
    "yemen" -> Res.string.country_yemen
    "zambia" -> Res.string.country_zambia
    "zimbabwe" -> Res.string.country_zimbabwe
    else -> Res.string.country_argentina // fallback
}
